language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.7
  - DJANGO=1.8
env:
  - DJANGO=1.7 DJANGO_VERSION_MIN=1.7 DJANGO_VERSION_MAX=1.8
  - DJANGO=1.8 DJANGO_VERSION_MIN=1.8 DJANGO_VERSION_MAX=1.9
install:
  - pip install -q "Django>=$DJANGO_VERSION_MIN,<$DJANGO_VERSION_MAX"
script: python manage.py test
